### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by Willtech** [Elinvention/gnome-shell-extension-nasa-apod#26]
No complaint about the image quality, the recent selections have been especially high quality.

I notice with this image loaded for desktop wallpaper my system RAM in use jumps from ~1GB to ~5.5GB with nothing else running which is strange considering the image is only ~215MB itself. This affects performance significantly.
https://apod.nasa.gov/apod/ap191023.html

Please remember to include this informations in your bug report:

ASUS S400CA Ultrabook w/ DVMT Pre-Allocate set to 64M
VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

- Fedora 30
- GNOME Shell 3.32.2
- Installation method via Gnome Software and using top-icons-plus

**Comment by Elinvention** [comment]
Could you post an image of your system monitor with processes sorted by memory usage when you incur in this high memory usage issue?

**Comment by Willtech** [comment]
![Screenshot from 2019-11-04 13-50-05](https://user-images.githubusercontent.com/1173622/68097278-41310c00-ff0a-11e9-80f2-27923e689c04.png)

**Comment by Willtech** [comment]
And the comparison with a normal <1MB wallpaper:
![Screenshot from 2019-11-04 14-01-29](https://user-images.githubusercontent.com/1173622/68097549-b9e49800-ff0b-11e9-83df-75af70f6a74f.png)


I suspect this may be an upstream issue but, always start at the beginning.

**Comment by Elinvention** [comment]
The extension's code is run inside the gnome-shell process. As you can see the RAM usage of gnome-shell is about the same in both situations (actually it's higher in the second image), so we can exclude it is being caused by the extension. 

However it is strange because the top process (packagekitd) is using just 5.7% and I can't really see what adds up to 5GB.

Also gnome-shell is using 10% of CPU which is really abnormal. This high CPU usage could indeed be caused by an extension. All I can say is try to disable one by one and see if the issue persists.

**Comment by Elinvention** [comment]
Stale. Feel free to reopen if the issue persists.

**Comment by Willtech** [comment]
I only find that the issue comes and goes with changing the background to large and small format using the extension.
